module.exports = async ({ go, ev, files, shot, sleep, key, win }) => {
  const dbg = win.webContents.debugger;
  await go('http://localhost:3000/', 1680, 1050);
  await ev(`localStorage.setItem('fontseru.appMode','font'); true`);
  await go('http://localhost:3000/', 1680, 1050);
  await files('input[type=file]', __dirname + '/StackSansNotch.ttf');
  await sleep(4500);
  await ev(`document.querySelectorAll('[class*=toast] button').forEach(b=>b.click()); document.querySelector('[data-testid="glyph-tile-a"]').click(); document.querySelector('[data-testid="tool-brush"]').click(); true`);
  await sleep(800);
  await shot('x-brush');
  await ev(`[...document.querySelectorAll('.fm-topbar button')].find(b=>b.textContent.trim()==='Family').click(); true`);
  await sleep(1500);
  await shot('x-family');
  await ev(`document.querySelector('[data-testid="family-auto-close"]').click(); [...document.querySelectorAll('.fm-topbar button')].find(b=>b.textContent.includes('Feature Builder')).click(); true`);
  await sleep(1500);
  await shot('x-feature');
  await ev(`document.querySelector('[data-testid="feature-builder-close"]').click(); true`);
  await sleep(500);
  await ev(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Multilingual Glyphs')).click(); true`);
  await sleep(1500);
  await shot('x-multi');
  await ev(`document.querySelector('[data-testid="test-lab-btn"]').click(); true`);
  await sleep(1500);
  await ev(`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Kerning Pairs').click(); true`);
  await sleep(1200);
  await shot('x-kern');
};
